# -*- coding: utf-8 -*-
"""tf-to-tflite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhcY95a-o0_cYhgrIs2_icuXVD3UOgqk
"""

import os
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
!pwd
!ls

My_TFlite_Model = tf.keras.models.load_model('Covid_model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(My_TFlite_Model)
tflite_model = converter.convert()
open("My_TFlite_Model.tflite", "wb").write(tflite_model)

